// Curated subset of Brian Eno & Peter Schmidt's Oblique Strategies
// (1975). The full deck has ~100+ cards across editions; we keep the
// most quotable / least cryptic ones so the team gets a useful nudge
// when the moodboard starts feeling stuck.
export const OBLIQUE_CARDS: readonly string[] = [
  "Abandon normal instructions.",
  "Accept advice.",
  "Allow an easement (an easement is the abandonment of a stricture).",
  "Are there sections? Consider transitions.",
  "Ask people to work against their better judgment.",
  "Ask your body.",
  "Be dirty.",
  "Be extravagant.",
  "Be less critical more often.",
  "Bridges — build — burn.",
  "Cluster analysis.",
  "Consider different fading systems.",
  "Cut a vital connection.",
  "Decorate, decorate.",
  "Define an area as 'safe' and use it as an anchor.",
  "Discard an axiom.",
  "Disconnect from desire.",
  "Discover the recipes you are using and abandon them.",
  "Distorting time.",
  "Do nothing for as long as possible.",
  "Don't be afraid of things because they're easy to do.",
  "Don't be frightened to display your talents.",
  "Don't break the silence.",
  "Emphasize differences.",
  "Emphasize the flaws.",
  "Faced with a choice, do both.",
  "Find a safe part and use it as an anchor.",
  "Go to an extreme, move back to a more comfortable place.",
  "Honor thy error as a hidden intention.",
  "How would you have done it?",
  "Humanize something free of error.",
  "Idiot glee.",
  "Imagine the music as a moving chain or caterpillar.",
  "Infinitesimal gradations.",
  "Is it finished?",
  "Is there something missing?",
  "Just carry on.",
  "Listen to the quiet voice.",
  "Look closely at the most embarrassing details and amplify them.",
  "Make a sudden, destructive, unpredictable action; incorporate.",
  "Make it more sensual.",
  "Mute and continue.",
  "Not building a wall but making a brick.",
  "Once the search is in progress, something will be found.",
  "Only one element of each kind.",
  "Remember those quiet evenings.",
  "Remove specifics and convert to ambiguities.",
  "Repetition is a form of change.",
  "Retrace your steps.",
  "Reverse.",
  "Short circuit.",
  "Simple subtraction.",
  "Tape your mouth.",
  "The most important thing is the thing most easily forgotten.",
  "Think of the radio.",
  "Towards the insignificant.",
  "Try faking it.",
  "Turn it upside down.",
  "Use an old idea.",
  "Use 'unqualified' people.",
  "Voice your suspicions.",
  "What context would make this seem useful?",
  "What is the simplest solution?",
  "What mistakes did you make last time?",
  "What would your closest friend do?",
  "What wouldn't you do?",
  "Work at a different speed.",
  "You are an engineer.",
  "You don't have to be ashamed of using your own ideas.",
  "Your mistake was a hidden intention.",
];

export function pickObliqueCard(exclude?: string | null): string {
  const pool =
    exclude && OBLIQUE_CARDS.includes(exclude)
      ? OBLIQUE_CARDS.filter((c) => c !== exclude)
      : OBLIQUE_CARDS;
  return pool[Math.floor(Math.random() * pool.length)] ?? OBLIQUE_CARDS[0];
}
